### ISSUE TITLE
Error: ME Analyzer crashed

### ISSUE THREAD

**Issue by hotchpocker** [platomav/MEAnalyzer#12]
Hi!
Windows 10 Pro  64. Python Python 3.7.3 . I decomress new Dell Latitude bios 3570. After  -mass option, choose path , then Enter , some file checked, then stop with that mistake.

Error: ME Analyzer crashed, please report the following:
Traceback (most recent call last):
  File "MEA.py", line 8775, in <module>
    oem_config,oem_signed,cpd_mn2_info,ext_iunit_val = ext_anl(reading, '$MN2', start_man_match, file_end, [variant, major, minor, hotfix, build], None) # Get CSE Attributes
  File "MEA.py", line 4946, in ext_anl
    if mod_data == b'\xFF' * mod_size or cpd_entry_offset >= file_end : mod_empty = 1 # Determine if Module is Empty/Missing
OverflowError: cannot fit 'int' into an index-sized integer

**Comment by hotchpocker** [comment]
After unpacked section_3_11.8.55.3510.data , there are folder Unpacked_section_3_11.8.55.3510.data. In that folder file FTPR.man - is reason issue.

**Comment by platomav** [comment]
You haven't unpacked the HDR executable properly. Use [Dell HDR Module Extractor](https://github.com/platomav/BIOSUtilities) to unpack the HDR executable. The proper CSME firmware file is called "4_Intel_Management_Engine_(Non-VPro)_Update_11.8.55.3510.data".

**Comment by HackerajOfficial** [comment]
https://youtu.be/CecJuIGLQtQ?si=CJCJ1HohzNZfiPkD

Simple, ME Region need to be repair manually, or using any Tool.
