### ISSUE TITLE
Exit status is 0 when no ME detected

### ISSUE THREAD

**Issue by hughsie** [platomav/MEAnalyzer#13]
This is how you can reproduce:

    $ python3 ./MEA.py Changelog.txt -skip -redir
    +------------------------------------------+
    |         ME Analyzer v1.85.0 r162         |
    +------------------------------------------+

    +---------------------+
    | Changelog.txt (1/1) |
    +---------------------+

    File does not contain Intel Engine firmware

    $ echo $?
    0

**Comment by platomav** [comment]
MEA can support multiple files as input so it's not possible to have one exit value for all. For example, the third input might not contain engine firmware but the seventh might do. You can check if the message "File does not contain Intel Engine firmware" is displayed though.
