### ISSUE TITLE
[not an issue per se] ME FPT Header parser: I am in quest for v21 sample

### ISSUE THREAD

**Issue by nms42** [platomav/MEAnalyzer#21]
Sir,
did You have a sample of such beast (bios)?

**Comment by nms42** [comment]
Sorry,
discussion goes at win-raid forum. I must be asking there.

**Comment by platomav** [comment]
Indeed not an issue of MEA. FPT v2.1 will be present at Tiger Lake or newer CSE firmware so there are no public samples yet.
