### ISSUE TITLE
take yellow error and cannot use for analise firmware mei

### ISSUE THREAD

**Issue by pipes80-collab** [platomav/MEAnalyzer#24]
I take an message yellow when i install pyinstaller and cannot use for create mea.exe
![Immagine 2020-09-25 210122](https://user-images.githubusercontent.com/56699284/94306510-650e9d80-ff73-11ea-95a0-2ae658fd5214.png)

**Comment by platomav** [comment]
The yellow message tells you exactly what you need to do. [Add the Scripts path to the PATH local variable.](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/)

**Comment by pipes80-collab** [comment]
![Immagine 2020-09-26 011425](https://user-images.githubusercontent.com/56699284/94323339-b039a800-ff95-11ea-94f6-ceffcc195ac3.png)
now that error
