### ISSUE TITLE
add dg1 fw

### ISSUE THREAD

**Issue by zwlms** [platomav/MEAnalyzer#25]
╔═══════════════════════════════════════════╗
║         ME Analyzer v1.172.3 r216         ║
╚═══════════════════════════════════════════╝

╔═══════════════════════════════════════════════╗
║           dg1_gfx_fwupdate.bin (1/1)          ║
╟───────────────────────────────┬───────────────╢
║             Family            │      GSC      ║
╟───────────────────────────────┼───────────────╢
║            Version            │  100.0.0.1162 ║
╟───────────────────────────────┼───────────────╢
║            Release            │   Production  ║
╟───────────────────────────────┼───────────────╢
║              Type             │   Extracted   ║
╟───────────────────────────────┼───────────────╢
║              SKU              │    Slim LP    ║
╟───────────────────────────────┼───────────────╢
║            Chipset            │    Unknown    ║
╟───────────────────────────────┼───────────────╢
║  TCB Security Version Number  │       1       ║
╟───────────────────────────────┼───────────────╢
║  ARB Security Version Number  │       1       ║
╟───────────────────────────────┼───────────────╢
║     Version Control Number    │       2       ║
╟───────────────────────────────┼───────────────╢
║        Production Ready       │      Yes      ║
╟───────────────────────────────┼───────────────╢
║       OEM Configuration       │       No      ║
╟───────────────────────────────┼───────────────╢
║              Date             │   2020-08-16  ║
╟───────────────────────────────┼───────────────╢
║       File System State       │  Unconfigured ║
╟───────────────────────────────┼───────────────╢
║              Size             │    0x201000   ║
╟───────────────────────────────┼───────────────╢
║        Flash Image Tool       │  100.0.0.1162 ║
╟───────────────────────────────┼───────────────╢
║        Chipset Support        │      DG1      ║
╟───────────────────────────────┼───────────────╢
║             Latest            │      Yes      ║
╚═══════════════════════════════╧═══════════════╝
╔════════════════════════════════════════════╗
║        Power Management Controller         ║
╟─────────────────────────────┬──────────────╢
║            Family           │     PMC      ║
╟─────────────────────────────┼──────────────╢
║           Version           │ 10.0.00.1024 ║
╟─────────────────────────────┼──────────────╢
║           Release           │  Production  ║
╟─────────────────────────────┼──────────────╢
║             Type            │ Independent  ║
╟─────────────────────────────┼──────────────╢
║         Chipset SKU         │   Unknown    ║
╟─────────────────────────────┼──────────────╢
║       Chipset Stepping      │   Unknown    ║
╟─────────────────────────────┼──────────────╢
║ TCB Security Version Number │      0       ║
╟─────────────────────────────┼──────────────╢
║ ARB Security Version Number │      0       ║
╟─────────────────────────────┼──────────────╢
║    Version Control Number   │      1       ║
╟─────────────────────────────┼──────────────╢
║       Production Ready      │     Yes      ║
╟─────────────────────────────┼──────────────╢
║             Date            │  2020-08-20  ║
╟─────────────────────────────┼──────────────╢
║             Size            │    0x3000    ║
╟─────────────────────────────┼──────────────╢
║  Manifest Extension Utility │ 100.0.0.9000 ║
╟─────────────────────────────┼──────────────╢
║       Chipset Support       │     DG1      ║
╚═════════════════════════════╧══════════════╝

Warning: Could not find any File System FTBL/EFST Platform, assuming 01!

Warning: Could not find any File System FTBL/EFST Dictionary, assuming 0A!

Warning: Incompatible PMC DG1 firmware detected!

Note: This PMC DG1 firmware was not found at the database, please report it!

Note: This GSC firmware was not found at the database, please report it!
[fulldriver.cab](http://download.windowsupdate.com/c/msdownload/update/driver/drvs/2020/10/01e0e044-988c-41f8-b2a0-cbbdb149165c_6652270314a3ad20c555482c0b5d3c24576975cb.cab)
fw:cab\fw\dg1_gfx_fwupdate.bin

**Comment by platomav** [comment]
You're using an outdated MEA version, please update to the latest.
