### ISSUE TITLE
Failed to anlayze SPSv5.x

### ISSUE THREAD

**Issue by citypw** [platomav/MEAnalyzer#29]
File: https://ufile.io/sekaul4l

Reproducible steps:
1) Patch it under Ubuntu 20.04:

```
index be1edd1..1c01e88
--- a/MEA.py
+++ b/MEA.py
@@ -9480,7 +9479,7 @@ def mea_exit(code) :
 # Input Colorama Workaround (Windows, Python 3.5+)
 # https://github.com/tartley/colorama/issues/103#issuecomment-629816451
 def input_col(message) :
-       print(message, end = '')
+       print(message, end == '')
        input()
 
 # Calculate MD5 hash of data
```

2)

# python3 MEA.py -skip -dfpt | less
```
Error: ME Analyzer v1.204.0 crashed, please report the following:

Traceback (most recent call last):
  File "MEA.py", line 10521, in <module>
    elif sys_os.startswith('linux') or sys_os == 'darwin' : sys.stdout.write('\x1b]2;' + mea_title + '\x07')
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 184, in write_and_convert
    text = self.convert_osc(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 256, in convert_osc
    winterm.set_title(params[1])
AttributeError: 'NoneType' object has no attribute 'set_title'
```
#python3 MEA.py -skip -dfpt 
```
............
........
....
Error: Detected MFS Low Level File 364 which has not been parsed!

Error: Detected MFS Low Level File 365 which has not been parsed!

Error: Detected MFS Low Level File 366 which has not been parsed!

Error: Detected MFS Low Level File 367 which has not been parsed!

Error: Detected CSE Extension 0x16 with wrong Partition Hash at OPR > FTPR.man!
```

**Comment by platomav** [comment]
Thanks for the CSSPS 5 with Initialized VFS sample.

>print(message, end == '')

This change doesn't make sense. Parameter "end" must be a string, not (False) boolean.

>python3 MEA.py -skip -dfpt | less

Apparently "less" causes some incompatibility with color display. Avoid using it.

>Error: Detected MFS Low Level File xxx which has not been parsed!

These VFS errors happen at some CSSPS 4 & 5 because I don't know how to properly parse their Initialized File Systems.

>Error: Detected CSE Extension 0x16 with wrong Partition Hash at OPR > FTPR.man!

This error is normal/expected at CSSPS 5. Intel does not feel like fixing it.

**Comment by citypw** [comment]
Yeah, the patch doesn't make sense. Python2 complains but MEA should be run via Python3. So this is the issue from Intel, I'm closing the issue now. Thanks for the quick feedback.
