### ISSUE TITLE
Character encoding error. Tried on Windows 7 x64

### ISSUE THREAD

**Issue by uemil** [platomav/MEAnalyzer#3]
SyntaxError: Non-ASCII character '\xc2' in file MEA.py on line 233, but no encod
ing declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by platomav** [comment]
Line 233 is related to UEFIFind Engine GUID detection message printout. Are you using -enuf parameter? Also, provide a link to the file which causes that encoding error. The doc you mentioned is not relevant for Python 3.x, only 2.x where the default encoding was not UTF-8 but rather ASCII if I remember properly.

**Comment by uemil** [comment]
I didn't "mention the doc", I just copy pasted the output after runing the
script. Btw, it was the comments that made it hang, after cleanup, it
passed over it, but had other issues. Tomorrow I might post them if you
like.

**Comment by platomav** [comment]
Not sure I understand what problem the comments caused but ok, post what you found whenever you can.

**Comment by platomav** [comment]
@uemil Any news?
