### ISSUE TITLE
api-ms-win-core-path-l1-1-0.dll is missing in win7

### ISSUE THREAD

**Issue by 87zrjojo** [platomav/MEAnalyzer#30]
When I use the latest ME analyzer v1.253.0 r262,it always prompt that "api-ms-win-core-path-l1-1-0.dll is missing", and the older one has no such problem (such as "ME analyzer_ Analyzer_ v1.206.4"  ),What's the matter?

**Comment by platomav** [comment]
This is not a ME Analyzer issue, but something related to PyInstaller or the bundled python interpreter. My guess is Windows 7 is not supported.
