### ISSUE TITLE
How to download anything on github ?

### ISSUE THREAD

**Issue by tonycstech** [platomav/MEAnalyzer#36]
Please explain to me how to download compiled projects here on github ?
I never find a link to already compiled projects. All i find is source code. 
I cant compile it my self because i dont know what programs i need to do it but it seems to me that this is all there is.

This project description says i can download it by going to releases and provide a link, but when i follow that link, all i see is source code.
This is driving me nuts. For years i avoid github because there is no obvious way to download compiled windows executable.

**Comment by platomav** [comment]
https://github.com/platomav/MEAnalyzer#c-download-me-analyzer

**Comment by tonycstech** [comment]
That link does not help. I dont see any obvious way to download windows executable.
It says:
you don't need to manually build/freeze/compile ME Analyzer under Windows. Instead, download the latest version from the [Releases](https://github.com/platomav/MEAnalyzer/releases)
When i i click [Releases] i land on a page that gives source code only.
No executables.
