### ISSUE TITLE
Syntax error in /Users/username/MEA.py Mac OS

### ISSUE THREAD

**Issue by Galicia01** [platomav/MEAnalyzer#37]
Error on command, cannot continue :(

pyinstaller --noupx --onefile MEA.py

137 INFO: PyInstaller: 5.3
137 INFO: Python: 3.10.6
150 INFO: Platform: macOS-10.15.7-x86_64-i386-64bit
154 INFO: wrote /Users/username/MEA.spec
158 INFO: UPX is not available.
160 INFO: Extending PYTHONPATH with paths
['/Users/dannydegalicia']
402 INFO: checking Analysis
402 INFO: Building Analysis because Analysis-00.toc is non existent
402 INFO: Initializing module dependency graph...
405 INFO: Caching module graph hooks...
415 INFO: Analyzing base_library.zip ...
5123 INFO: Processing pre-find module path hook distutils from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
5165 INFO: distutils: retargeting to non-venv dir '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10'
6821 INFO: Caching module dependency graph...
6977 INFO: running Analysis Analysis-00.toc
6990 INFO: Analyzing /Users/username/MEA.py

Syntax error in /Users/username/MEA.py
  File "/Users/username/MEA.py", line 67
     <title>MEAnalyzer/MEA.py at master · platomav/MEAnalyzer · GitHub</title>
                                        ^
 SyntaxError: invalid character '·' (U+00B7)

**Comment by platomav** [comment]
> <title>MEAnalyzer/MEA.py at master · platomav/MEAnalyzer · GitHub</title>

That's clearly not python code, that "MEA.py" is invalid. You need to clone/download the repo properly first. Closing this as a non-issue.
