### ISSUE TITLE
Me Analyzer Not Working In Windows 10 Pro 64x

### ISSUE THREAD

**Issue by AragornKnight007** [platomav/MEAnalyzer#39]
I've installed all the python file and MEAnalyzer  successfully, But when i'm try to open MEA.py  A prompt  open and close in just few milliseconds, after that nothing happened

**Comment by platomav** [comment]
Open a command prompt in the folder where MEA.py is located and run it via "mea.py" to see what it says. You can then proceed accordingly to fix whatever is missing/wrong. This is definitely not MEA related, but something with Python installation, probably.
