### ISSUE TITLE
Not in database  11.6.27.3264

### ISSUE THREAD

**Issue by positr0nic** [platomav/MEAnalyzer#4]
```
-------[ ME Analyzer v1.11.1 ]-------
            Database r85

File:     116273264.bin

Family:   ME
Version:  11.6.27.3264
Release:  Production
Type:     Region, Stock
SKU:      Corporate H
Rev:      D0
VCN:      192
PV:       Yes
Date:     09/04/2017
Size:     0x702000
Platform: SPT/KBP
Latest:   No

Note: This firmware was not found at the database, please report it!

```

http://www.station-drivers.com/index.php?option=com_remository&Itemid=352&func=startdown&id=2829&lang=fr

**Comment by platomav** [comment]
Hello,

I am [aware](http://www.win-raid.com/t596f39-Intel-Management-Engine-Drivers-Firmware-amp-System-Tools-188.html#msg38297) and will be included at the next db release. Generally it's best if the [forum](http://www.win-raid.com/f39-Special-Intel-Management-Engine.html) is used for such inquires as the Issues page here is best suited for MEA bugs, suggestions etc.

Thank you for letting me know either way.

**Comment by positr0nic** [comment]
> Generally it's best if the forum is used for such inquires

Sorry, I dont use the forums, wherever that is.
