### ISSUE TITLE
MEAnalizer not working on W10

### ISSUE THREAD

**Issue by MataPuelc0s** [platomav/MEAnalyzer#41]
Just installed python and downloaded the files. Ran me.py through powershell on the folder where I threw the files. It opens another window then it closes inmediately. No more info about it.  What should I do? I just read the previous issue but no more info was provided to know how him got it to work.

**Comment by MataPuelc0s** [comment]
sorry about the duplicate issue.
Just did that. It throws this
![image](https://user-images.githubusercontent.com/56326550/213310570-1f2d61d5-f886-4ded-8e02-84007dda61ee.png)
Should I reinstall python then?

**Comment by platomav** [comment]
What version of Python as you using? Run `python --version` to check.

**Comment by MataPuelc0s** [comment]
installed 3.11.1

**Comment by platomav** [comment]
From the path, you must be using the microsoft store installation, which is known to be weird. Uninstall whatever python you have installed and download/install from the official python website instead:

https://www.python.org/downloads/

Don't forget the requirements afterward via pip, as explained in the README.

**Comment by MataPuelc0s** [comment]
Done as you suggested, even when my first install was from the official source (default path). Changed the install path to my C: drive root, installed modules there, but the error keeps preventing MEAnalizer from execution. I really dont have idea what's happening here. It should work as is right?

**Comment by platomav** [comment]
Yes, it should work just fine with Python 3.11 under Windows. Maybe the files are not downloaded properly. Try re-downloading and run from the extracted directory:

https://github.com/platomav/MEAnalyzer/archive/refs/heads/master.zip

**Comment by MataPuelc0s** [comment]
This time worked. I had to disable the application execution alias under Setup on windows. after doing that, the execution runs as expected. Thank you.
