### ISSUE TITLE
Feature requrest: don't exit after the analysis is complete and instead ask the user if they want to analyze another file

### ISSUE THREAD

**Issue by blunderful-scripts** [platomav/MEAnalyzer#47]
Hello, first - I've been using this tool for a long time now and it's fantastic!
To the feature request, the title says it all.

Good luck with further development and thank you!

**Comment by platomav** [comment]
Hello,

Admittedly, the input and output options in MEA are fairly limited, but there are options to handle that specific request. If you drag & drop multiple files, the "welcome" screen will say "multiple" and work with all of them. And for a more appropriate method, there is the "-mass" parameter. You can feed the latter a directory and all files within will be scanned.
