### ISSUE TITLE
Latest Firmware status missing

### ISSUE THREAD

**Issue by Fighter158** [platomav/MEAnalyzer#48]
How to add is an issue with Status of ME firmware. I have older exe file with this function.
![obrázek_2023-11-10_154534738](https://github.com/platomav/MEAnalyzer/assets/28108432/c9565c88-a9c5-4519-94f2-e976cef9618e)

**Comment by platomav** [comment]
Hello,

The "latest" status was removed as a feature around ~1.5 ago. I think [v1.278.0](https://github.com/platomav/MEAnalyzer/releases/tag/v1.278.0-r290) is the last version which retained that feature. Either way, that status is dependent on how frequently (and manually) someone set what is the "last" firmware versions. So, even if you were to use the last version with that feature, that status won't reflect reality anymore.
