### ISSUE TITLE
csme 16.0.15.1545 ( unsupported intel engine error)

### ISSUE THREAD

**Issue by arieslaptop** [platomav/MEAnalyzer#49]
Kindly please update for ver csme 16
![Screenshot_4](https://github.com/platomav/MEAnalyzer/assets/88767405/4021589c-4972-4aa8-8e62-6a5a7c0c2b34)

**Comment by platomav** [comment]
The README, section A3, explains which are the supported Engine firmware families/versions:

https://github.com/platomav/MEAnalyzer?tab=readme-ov-file#a3-supported-engine-firmware-familiesversions

**Comment by arieslaptop** [comment]
Thanks, sir, for your quick reply. Sorry for the late comment
