### ISSUE TITLE
Json output missing data...

### ISSUE THREAD

**Issue by KingBonecrusher** [platomav/MEAnalyzer#51]
Tested version: **MEAnalyzer-1.304.4-r338**

       "Platform Controller Hub Configuration": [
            "Entry 0000",
            "Entry 0001",
            "Entry 0002",
            "Entry 0003",
            "Entry 0004",
            "Entry 0005",
            "Entry 0006",
            "Entry 0007",
            "Entry 0008",
            "Entry 0009",
            "Entry 0010",
            "Entry 0011",
            "Entry 0012",
            "Entry 0013"

**Comment by platomav** [comment]
You much be using an outdated version of the "pltable" library dependency. Update via:

`python -m pip install --upgrade pltable`

**Comment by KingBonecrusher** [comment]
Correct, my fault! It`s wroking now!
