### ISSUE TITLE
Are HP a bunch of liars or is ME Analyzer failing to detect the firmware properly?

### ISSUE THREAD

**Issue by filamento** [platomav/MEAnalyzer#58]
Reading the description here:

https://support.hp.com/us-en/drivers/swdetails/hp-elitedesk-800-g2-small-form-factor-pc/7633277/swItemId/vc-305244-1

HP says that the bios upgrade includes version 11.8.70.3595 of intel ME

However, when you extract the BIN file and give it to ME Analyzer, it says:

"File does not contain Intel Engine/Graphics/Independent Firmware"

Who's telling the truth in this case? HP or ME Analyzer?

**Comment by platomav** [comment]
There is no CSME firmware within "N01_0260.bin"
