### ISSUE TITLE
increased functionality 

### ISSUE THREAD

**Issue by freecableguy** [platomav/MEAnalyzer#6]
Please add compatibility for SPS v3 (now limited to SPS>=4).  SPS 3 is used for platforms Haswell-E (Wellsburg) and is still very much in use today

**Comment by platomav** [comment]
MEA supports all SPS firmware from v1 to v4, not only the latter. What makes you think that v3 is not supported?

**Comment by freecableguy** [comment]
"Ability to unpack Engine x86 firmware (ME >= 11, TXE >= 3, SPS >= 4)"

**Comment by platomav** [comment]
Engine **x86** includes all firmware generations which run on top of Intel's Converged Security Engine (CSE), which is x86-based. That means ME 11+, TXE 3+ and SPS 4+. The previous generations were ARC (ME 1-10) or SPARC (TXE1-2) based. SPS 2-3 are based on ME 6, thus not Engine x86.

For pre-x86 firmware generations, you can use @skochinsky 's [me_unpack](https://github.com/skochinsky/me-tools) instead.

**Comment by freecableguy** [comment]
Thank you. Withdrawn
